image:
  file: .gitpod.Dockerfile
  context: .
tasks:
  - init: |
      mkdir $HOME/bin
      ln -s /theia/supervisor $HOME/bin/newuidmap
      ln -s /theia/supervisor $HOME/bin/newgidmap
      export PATH=$HOME/bin:$PATH
      go get github.com/rootless-containers/rootlesskit/cmd/rootlesskit
      curl -fsSL https://get.docker.com/rootless | SKIP_IPTABLES=1 sh